### ISSUE TITLE
Re-add "spa" TLD

### ISSUE THREAD

**Issue by pgporada** [weppos/publicsuffix-go#487]
Hi,

The `spa` TLD has been activated again per https://www.iana.org/reports/tld-transfer/20201016-spa . We've seen at least one failed certificate issuance @ Let's Encrypt due to this TLD still be marked as disabled in `rules.go` https://github.com/weppos/publicsuffix-go/blob/master/publicsuffix/rules.go#L7089 . I ran the generator, but it didn't re-enable the TLD. Should I manually edit `rules.go` and submit a PR?

**Comment by weppos** [comment]
HI @pgporada, I am not sure what you mean with _marked as disabled_, given there's no such thing in the definition structure.

Definitions are pulled daily from the main PSL file. The fact you run the generator and did not produce a difference is likely because the current list is up to date.
