### ISSUE TITLE
http://google.com give http://google.com

### ISSUE THREAD

**Issue by Frantch** [weppos/publicsuffix-go#545]
Hi,

Is it normal that `publicsuffix.EffectiveTLDPlusOne("http://google.com)` gives as a result `http://google.com`and not simply `google.com` ?

Thank you

**Comment by weppos** [comment]
> Hi,
> 
> Is it normal that `publicsuffix.EffectiveTLDPlusOne("http://google.com)` gives as a result `http://google.com`and not simply `google.com` ?
> 
> Thank you

Yes, the string you supplied as input is not a valid domain name as it also contain the scheme. This library is not designed to replace an URL parsing system, therefore you are expected to provide as argument just a name and deal with the URL decomposition separately.

If you don't you may get inconsistent results.

**Comment by Frantch** [comment]
got it, thank you
