### ISSUE TITLE
Domains with consecutive dots (empty labels)

### ISSUE THREAD

**Issue by Justin-Marks** [weppos/publicsuffix-go#567]
https://publicsuffix.org/list/
> A domain or rule can be split into a list of labels using the separator "." (dot). The separator is not part of any of the labels. **Empty labels are not permitted**, meaning that leading and trailing dots are ignored.

`Parse` currently doesn't accept `.google.com` (leading empty label) or `google.com.` (trailing empty label) but accepts `google..com` (interior empty label)

```
publicsuffix.Parse("google..com")

Output:
TLD = "com"
SLD = ""
TRD = "google"
```

Is this normal?

**Comment by Justin-Marks** [comment]
Also, `google.com.` is a valid domain name so I think `Parse` should accept it. The definition merely states trailing dots are to be _ignored_, so `google.com.` could be treated as `google.com`

On a related note, would it be appropriate for `Parse` to do minimum domain name validation such as checking the length of the domain name and its labels (https://datatracker.ietf.org/doc/html/rfc2181#section-11) or is that out of scope?

**Comment by Justin-Marks** [comment]
> This package also aims for 100% compatibility with the x/net package.

The x/net package returns an error:
https://go.dev/play/p/EW2_SqApQ7R

**Comment by weppos** [comment]
At the time being, I have no plan to start introducing extensive validations. It goes beyond the scope of the library.
If you pass an invalid string, it either means you trust user input, or the program is incorrectly manipulating data.

In the first scenario, you can add your own validations [like in this example](https://github.com/weppos/publicsuffix-go/issues/567).

**Comment by vladtreny** [comment]
It doesn't mean both. Your thinking is very limited
