### ISSUE TITLE
Fail to extract eTLD from s3-us-west-1.amazonaws.com

### ISSUE THREAD

**Issue by FrancescoFerro** [weppos/publicsuffix-go#657]
Hi,

Stumbled into some kind of wierd issue.

This fails
`publicsuffix.EffectiveTLDPlusOne("s3-us-west-1.amazonaws.com")`

This doesn't fail
`publicsuffix.EffectiveTLDPlusOne("s1-us-west-1.amazonaws.com")`

This doesn't fail
`publicsuffix.EffectiveTLDPlusOne("s3-us-west-1.google.com")`

This doesn't fail
`publicsuffix.EffectiveTLDPlusOne("s3-us-hello-1.amazonaws.com")`

I thought I had found a workaround by doing 
`publicsuffix.EffectiveTLDPlusOne("https://s3-us-west-1.amazonaws.com")`

But then this doesn't work
`publicsuffix.EffectiveTLDPlusOne("https://google.com")`

**Comment by weppos** [comment]
`s3-us-west-1.amazonaws.com` is listed as public suffix:

https://github.com/publicsuffix/list/blob/c492e2d388e7b87087f0aec3ef64a20bd24ac65f/public_suffix_list.dat#L10746

The other hostnames you mentioned are not.
