### ISSUE TITLE
Domain validation

### ISSUE THREAD

**Issue by vladtreny** [weppos/publicsuffix-go#676]
Hello, is it possible to add domain validation for such cases?

	dom, err := publicsuffix.Domain("adsbygoogle || []).push({});")
	fmt.Println(dom, err)

**Comment by weppos** [comment]
Validations are beyond the scope. You can leverage the `url` package or more specific URI validators.

```go
package main

import (
	"fmt"
	"net/url"
)

func main() {
	uri, err := url.Parse("adsbygoogle || []).push({});")
	if err != nil || uri.Host == "" {
		fmt.Println("Invalid host")
	}

        dom, _ := publicsuffix.Domain(uri.Host)
	fmt.Println(dom)
}
```
