### ISSUE TITLE
`.za` not recognized as an IANA country code

### ISSUE THREAD

**Issue by cpu** [weppos/publicsuffix-go#87]
Hi there, :wave:

It's possible I'm missing something obvious but it looks like `.za` is not being recognized as an IANA country code.

Here's my test program:
```
package main

import (
	"fmt"

	"github.com/weppos/publicsuffix-go/publicsuffix"
)

func main() {
	opts := &publicsuffix.FindOptions{
		IgnorePrivate: true,
		DefaultRule:   nil,
	}
	for _, d := range []string{"foo.ca", "foo.za"} {
		rule := publicsuffix.DefaultList.Find(d, opts)
		fmt.Printf("%s -> %#v\n", d, rule)
	}
}
```

And the resulting output:
```
foo.ca -> &publicsuffix.Rule{Type:1, Value:"ca", Length:1, Private:false}
foo.za -> (*publicsuffix.Rule)(nil)
```

Based on [the IANA root db](https://www.iana.org/domains/root/db) entry for `.za`:
> .za | country-code | ZA Domain Name Authority

I would have expected a non-nil return from the call to `Find` given the `FindOptions` provided.

Is this a bug or a misunderstanding on my part?

Thanks!

**Comment by jsha** [comment]
You want to check the actual public suffix list: https://publicsuffix.org/list/public_suffix_list.dat. According to that, foo.za is not a valid domain name, similar to how foo.uk wouldn't be. All .za names are expected to be under one of a handful of second level domains:

```
// za : http://www.zadna.org.za/content/page/domain-information
ac.za
agric.za
alt.za
co.za
edu.za
gov.za
grondar.za
law.za
mil.za
net.za
ngo.za
nis.za
nom.za
org.za
school.za
tm.za
web.za
```

Because these are broken out individually in the public suffix list, "za" by itself isn't a public suffix. Do you have an example of a registered domain name that breaks this rule?

**Comment by cpu** [comment]
Aha! Thanks @jsha 

> Do you have an example of a registered domain name that breaks this rule?

I don't!

**Comment by weppos** [comment]
It looks like I was late to the party.

What @jsha is correct. Some TLDs have no second-level registrations at all. That's the case (as of today, for out knowledge) for the .ZA TLD.

Other TLDs may force users to use a third-level registration, but they may be using second-level domains for certain cases. This may happen for example for the registry site, or sites reserved to government. 

If you should find any .ZA domain registered at the second level that is not served via third level, then let me know and we'll see how to update the list accordingly.

Thanks to both for the question and answer.

**Comment by cpu** [comment]
@weppos Perfect! Thanks for confirming. That makes sense.

I haven't encountered any domains that serve as a counter-example to what yourself and Jsha said. For background to make this a complete story I was thrown by some test data that was generated using IANA suffixes that didn't associate `.za` with this third-level constraint and produced invalid examples (`foo.za`, etc).
