### ISSUE TITLE
autopull schedule?

### ISSUE THREAD

**Issue by futureweb** [weppos/publicsuffix-go#89]
Hey there,
may I ask when the autpopull of the PSL List is normally scheduled?
Need to get https://github.com/publicsuffix/list/pull/498 in. ;-)
thx, bye from Austria
Andreas

**Comment by futureweb** [comment]
plz forget ... seems like I'm blind ... ! :-/

**Comment by weppos** [comment]
The auto pull runs nightly, and creates a single PR for manual review. I generally review the PR the same day.
